### ISSUE TITLE
Not able to download or open any YT link

### ISSUE THREAD

**Issue by scropion86** [sooros5132/yt-dlp-web#11]
Hi

I am Not able to download or open any YT link
i have tried with users and pass also without it , and getting same result
the webui is appearing normall but can't do anything

i am running it on docker desktop on windows machine

### my docker env var

![image](https://github.com/user-attachments/assets/a0c74a83-6ce5-4bd2-902e-71be86e55e56)

### my docker log

`      
  ▲ Next.js 14.2.13
  - Local:        http://localhost:3000
  - Network:      http://0.0.0.0:3000
 ✓ Starting...
 ✓ Ready in 160ms
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at /app/.next/server/chunks/881.js:368:50420
    at or (/app/.next/server/chunks/881.js:368:53014)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at /app/.next/server/chunks/881.js:368:50420
    at or (/app/.next/server/chunks/881.js:368:53014)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)
new process, `35`
new process, `47`
[auth][error] MissingSecret: Please define a `secret`. Read more at https://errors.authjs.dev#missingsecret
    at /app/.next/server/chunks/881.js:368:50420
    at or (/app/.next/server/chunks/881.js:368:53014)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:538:9)
    at process.processTimers (node:internal/timers:512:7)`

**Comment by sooros5132** [comment]
I don't know because I haven't tested it on Windows
Did you set the volume of `download` and `cache` in `docker-compose.yml`?
A download folder and a cache folder are required for yt-dlp-web to operate correctly.

The example syntax is as follows.
```YML
# ~
volumes:
  - ~/Desktop/downloads:/downloads
  - ~/Desktop/cache:/cache
# ~
```
